export const Permissions = {
  DASHBOARD_VIEW: "dashboard:view",
  POS_SALE_CREATE: "pos:sale:create",
  POS_PRODUCT_SEARCH: "pos:product:search",
  INVENTORY_VIEW: "inventory:view",
  INVENTORY_EDIT: "inventory:edit",
  PURCHASE_VIEW: "purchase:view",
  PURCHASE_EDIT: "purchase:edit",
  CUSTOMER_VIEW: "customer:view",
  CUSTOMER_EDIT: "customer:edit",
  SUPPLIER_VIEW: "supplier:view",
  SUPPLIER_EDIT: "supplier:edit",
  SALES_VIEW: "sales:view",
  SALES_HOLD_EDIT: "saleshold:edit",
  STAFF_VIEW: "staff:view",
  STAFF_EDIT: "staff:edit",
  RETURN_VIEW: "return:view",
  RETURN_CREATE: "return:create",
  RETURN_APPROVE: "return:approve",
  COUNTER_VIEW: "counter:view",
  COUNTER_EDIT: "counter:edit",
  ATTENDANCE_SELF: "attendance:self",
  ATTENDANCE_ADMIN: "attendance:admin",
  REPORT_OVERVIEW: "report:overview",
  REPORT_SALES: "report:sales",
  REPORT_GST: "report:gst",
  REPORT_INVENTORY: "report:inventory",
  EXPENSE_VIEW: "expense:view",
  EXPENSE_EDIT: "expense:edit",
  ACTIVITY_VIEW: "activity:view",
  SETTINGS_VIEW: "settings:view",
  SETTINGS_EDIT: "settings:edit",
  UPLOAD_PRESCRIPTION: "upload:prescription",
  UPLOAD_LOGO: "upload:logo",
};

export const RolePermissions = {
  Admin: ["*"],
  Cashier: [
    Permissions.DASHBOARD_VIEW,
    Permissions.POS_SALE_CREATE,
    Permissions.POS_PRODUCT_SEARCH,
    Permissions.INVENTORY_VIEW,
    Permissions.CUSTOMER_VIEW,
    Permissions.CUSTOMER_EDIT,
    Permissions.SALES_VIEW,
    Permissions.SALES_HOLD_EDIT,
    Permissions.COUNTER_VIEW,
    Permissions.COUNTER_EDIT,
    Permissions.ATTENDANCE_SELF,
    Permissions.REPORT_SALES,
    Permissions.RETURN_VIEW,
    Permissions.RETURN_CREATE,
    Permissions.EXPENSE_VIEW,
    Permissions.SETTINGS_VIEW,
    Permissions.UPLOAD_PRESCRIPTION,
  ],
  Pharmacist: [
    Permissions.DASHBOARD_VIEW,
    Permissions.POS_SALE_CREATE,
    Permissions.POS_PRODUCT_SEARCH,
    Permissions.INVENTORY_VIEW,
    Permissions.CUSTOMER_VIEW,
    Permissions.CUSTOMER_EDIT,
    Permissions.SALES_VIEW,
    Permissions.SALES_HOLD_EDIT,
    Permissions.RETURN_VIEW,
    Permissions.RETURN_CREATE,
    Permissions.RETURN_APPROVE,
    Permissions.COUNTER_VIEW,
    Permissions.COUNTER_EDIT,
    Permissions.ATTENDANCE_SELF,
    Permissions.REPORT_OVERVIEW,
    Permissions.REPORT_SALES,
    Permissions.REPORT_GST,
    Permissions.REPORT_INVENTORY,
    Permissions.EXPENSE_VIEW,
    Permissions.SETTINGS_VIEW,
    Permissions.UPLOAD_PRESCRIPTION,
  ],
  "Inventory Manager": [
    Permissions.DASHBOARD_VIEW,
    Permissions.INVENTORY_VIEW,
    Permissions.INVENTORY_EDIT,
    Permissions.PURCHASE_VIEW,
    Permissions.PURCHASE_EDIT,
    Permissions.SUPPLIER_VIEW,
    Permissions.COUNTER_VIEW,
    Permissions.ATTENDANCE_SELF,
    Permissions.REPORT_INVENTORY,
    Permissions.SETTINGS_VIEW,
  ],
  Delivery: [Permissions.DASHBOARD_VIEW, Permissions.ATTENDANCE_SELF],
};
